### ISSUE TITLE
Outlines render improperly

### ISSUE THREAD

**Issue by mastercoms** [mastercomfig/tf2-patches#1]
They dont get attached to the models for spawn xrays

**Comment by Yttrium-tYcLief** [comment]
Wasn't this new for JI? Was this possibly added post-leak?

**Comment by micwoj92** [comment]
@Yttrium-tYcLief you mean the player outlines? They were added way before JI

**Comment by Yttrium-tYcLief** [comment]
This issue refers to the ones that get added to all allies temporarily when you spawn, I think. That one was either added in JI or MYM.

**Comment by micwoj92** [comment]
MYM. quick internet search shows threads from 2016

**Comment by Yttrium-tYcLief** [comment]
Looks like it. Tagging properly now.
