### ISSUE TITLE
Licensing Terms for Contributors

### ISSUE THREAD

**Issue by JulioC** [mastercomfig/tf2-patches#102]
What is the license applied to changes and improvements added to the original code?

The LICENSE includes the "SOURCE 1 SDK LICENSE". Does it apply to code created by non-Valve authors?

**Comment by micwoj92** [comment]
With the wave of contributors there definitely should be contributing.md.

**Comment by maximsmol** [comment]
You can assume that the licensing for all the Valve code here is All Rights Reserved by Valve Software. We need to add a contributing file stating that people give up certain rights of their own though I guess so nobody decides to randomly sue us for using their typo PR
