### ISSUE TITLE
Enable the unused upgrade station music 

### ISSUE THREAD

**Issue by Melonenyoshi** [mastercomfig/tf2-patches#139]
https://www.youtube.com/watch?v=Q7eJg7hRvqE
Would be played near the Upgrade Station music

**Comment by Melonenyoshi** [comment]
and i dont know how to add a label if i should have done that

**Comment by micwoj92** [comment]
Don't worry, @Yttrium-tYcLief does that. The repo needs to be configured to automatically give enhancement or bug label.

**Comment by micwoj92** [comment]
bruh

**Comment by Melonenyoshi** [comment]
ok thank you

**Comment by maximsmol** [comment]
Can't tell if this can be considered a bug, hence RFC
