### ISSUE TITLE
PKGBUILD for AUR

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/tf2-patches#167]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see cool software but it is not in AUR

**Describe the solution you'd like**
After #140 get's merged, create PKGBUILD for the superior Gnu/Linux distribution.

**Describe alternatives you've considered**
Upload to AUR

**Additional context**
I use arch btw

**Comment by melvyn2** [comment]
srsly

**Comment by micwoj92** [comment]
Why the downvotes? I've seen 3 pkgbuilds for source mods/games and all were trash and didnt install correctly. This project can succeed!!!!

**Comment by int-72h** [comment]
This requires TF2 to be installed. It would be very finnicky to get an AUR package as you'd need to find the location of TF2 which would need to manually put in. Also, to uninstall, you'd need to put back the old game, which could be done via hooks but it's not worth.

**Comment by micwoj92** [comment]
> This requires TF2 to be installed. It would be very finnicky to get an AUR package as you'd need to find the location of TF2 which would need to manually put in. Also, to uninstall, you'd need to put back the old game, which could be done via hooks but it's not worth.

this could be achieved by simple "tc2.install", example

```
post_install() {
	cat <<- EOF
		:: You need TF2 files at location x to play
		 ::Put them into this folder or change $y in PKGBUILD
		::in order to install somewhere else
	EOF
}
```

**Comment by int-72h** [comment]
In that case, maybe I'll write it.

**Comment by maximsmol** [comment]
Can anyone vouch to AUR being okay with projects that have "interesting" legal standing?

**Comment by melvyn2** [comment]
I really think that this was a joke, and a pkgbuild wouldn't integrate nicely with steam (even if you got it to work, it'd break all kinds of stuff, file lists and dependencies off the top of my head). From a legal standpoint, the AUR only hosts the build scripts, so it should be fine.

**Comment by int-72h** [comment]
> I really think that this was a joke, and a pkgbuild wouldn't integrate nicely with steam (even if you got it to work, it'd break all kinds of stuff, file lists and dependencies off the top of my head). From a legal standpoint, the AUR only hosts the build scripts, so it should be fine.

This is what I thought mainly.
Unless it just builds it, I can't imagine much easy practicality.

**Comment by RicochetYT** [comment]
+1
This would be really sweet in the longrun and would make stuff easier for me. My main PC is running Manjaro (Arch Based) so I could just use my laptop running Linux Mint to test TC2 instead. It would be good for performance testing since the laptop is very low-end and struggles with current-day TF2 with Mastercomfig.
So, while this is a good idea, I think manual installation isn't that big of a deal, unless you want to build TC2 on Arch.

**Comment by int-72h** [comment]
If we have a seperate launcher/client/installer program we could use the AUR for *that*.

**Comment by micwoj92** [comment]
> If we have a seperate launcher/client/installer program we could use the AUR for _that_.

Why? there are many packages that require manual intervention.

**Comment by melvyn2** [comment]
> > If we have a seperate launcher/client/installer program we could use the AUR for _that_.
> 
> Why? there are many packages that require manual intervention.

So? Why should we follow a bad example?

**Comment by micwoj92** [comment]
> > Why? there are many packages that require manual intervention.
> 
> So? Why should we follow a bad example?

How is that a bad example? I think you misunderstood me. By manual intervention mean that package requires something more than just `$pacman_wrapper -Syu`. ALL, ALL instructions on Arch wiki will tell you to manually download pkgbuild, inspect PKGBUILD, install depends and then make the package. Want an example of package that requires manual intervention? Literally every one that has some sort of customization from makeflags. Just because most users do not do it ut does not mean it is wrong. Another example are games, where paid games from gog or humble bundle require you to either place the (usually) .deb file in the directory or follow some instruction in automatic download script. My last example will be source ports(can TC2 qualify as one?) Where you can build the FOSS engine but still provide gamedata yourself.

**Comment by int-72h** [comment]
Manual intervention is not preferred- a separate installer could be cross-distro/platform as well.
