### ISSUE TITLE
Crash on map load

### ISSUE THREAD

**Issue by aaalek** [mastercomfig/tf2-patches#210]
### Description
Game crashes to desktop when loading into a map with an engine error where it can't find a random model, searches for error.mdl and cannot load it either.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the lastest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. Not sure if its reproducible but I downloaded a fresh install of TF2 to not have any leftover config files, put the TC2 files inside and tried running it. Trying to load into anything just crashes the game.

### Screenshots
![image](https://user-images.githubusercontent.com/37019558/93502555-2e9fa580-f917-11ea-98a5-4ca28394d430.png)

### Setup Details
- *Server or client:* Client
- *Operating system:* Windows 10
- *Team Comtress version:* 0.0.16
- *Custom content:* None
- *Launch options:* None

- *Graphics driver:* AMD RX560 20.4.2 Driver
- *DirectX level:* 100

### Performance Details

- *GPU model: AMD RX560 2 GB
- *CPU model:* AMD FX-4320
- *RAM amount:* 12GB
- *TF2 installed on:* HDD
- *TC2 installed on:* HDD (On desktop)
- *TC2 installation method:* Basic

**Comment by PDAleksa** [comment]
Update: So far i can only load into cp_cloak without any errors, everything else either gives a model error, or a script error

**Comment by treacherousfiend** [comment]
I'm not sure if this is reproducible, but several people have reported this issue.
Where did you download comtress from? Just want to make sure you didn't install the source code by accident.

Unrelated, but the checklist in github works like an actual checkbox lol, you aren't supposed to write yes or no in it.

**Comment by PDAleksa** [comment]
Sorry, didn't know about the checklist. I downloaded game_clean.zip

**Comment by treacherousfiend** [comment]
Well, that is correct... Unfortunately I have no other thoughts on what the problem could be, the only person off the top of my head who fixed it did so by reinstalling it like 5 times, which I wouldn't recommend.

**Comment by Yttrium-tYcLief** [comment]
>Not sure if its reproducible but I downloaded a fresh install of TF2 to not have any leftover config files 
That does not ensure leftover configs.

Does it happen when you launch the game with `-default` added to `start_tf2.bat`?

Have you tried a *clean* install, using the [advanced install instructions](https://github.com/mastercomfig/team-comtress-2/wiki/Advanced-Installation-Instructions)?

**Comment by RicochetYT** [comment]
I've heard horror stories of Github producing corrupt archive downloads entirely through the website, which is one of the reasons (iirc) that Open Fortress has its own repo you can download from now.

**Comment by micwoj92** [comment]
> I've heard horror stories of Github producing corrupt archive downloads entirely through the website, which is one of the reasons (iirc) that Open Fortress has its own repo you can download from now.

Then either they are wrong or your recall makes no sense. If they provided binaries with github tags, then it is THEIR responsibility. Github only makes source zips and .tar.gz archives and only problems that I have heard of was that these could have been remade and that would result in shasums changed.

**Comment by PDAleksa** [comment]
I tried using -default launch option, didn't work same error.
Downloaded the game again using DepotDownloader and downloaded TC2 0.0.16 for it. After it not working either i tried downloading 0.0.15 update which didn't work either. Something interesting that did happen is when starting the game with start_tf2.bat for the first time, Windows Defender says the file might be malicious.

**Comment by PDAleksa** [comment]
I did some more testing, and it seems completely random at this point whether it works or not. I can sometimes manage to load into cp_cloak and background01 without a problem, sometimes it just crashes instantly, and the furthest I've gotten to load into ctf_2fort was getting into a broken motd screen where I could see the map in the background which was also missing walls, and had missing textures on props, after that I would be in a broken class selection screen and after picking a class the game crashes to desktop with the engine error where it can't load models. I had an error message once where it said it couldn't load the Jungle Wreath hat for heavy, but going into my backpack to inspect the item and having the heavy wear it went just fine.

**Comment by Juesto** [comment]
> I've heard horror stories of Github producing corrupt archive downloads entirely through the website, which is one of the reasons (iirc) that Open Fortress has its own repo you can download from now.

those issues are related to core.autocrlf=true being a default in Git for Windows, causing pushed and index files from those systems to be LF and in some cases: mac resource fork blobs which happens with resource folder txts by default
