### ISSUE TITLE
Solutions generated by vpc don't work properly with msbuild

### ISSUE THREAD

**Issue by Margen67** [mastercomfig/tf2-patches#318]
### Description
When you try to build `games.sln` with msbuild it says it succeeds, but doesn't actually do anything.

### Checklist
- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [x] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. https://github.com/mastercomfig/team-comtress-2/wiki/Windows-Build-Instructions#building up to Step 8.
2. Open `Developer Command Prompt/PowerShell for VS 2019`
3. `cd` to `games.sln` directory
4. Run `msbuild games.sln`

However, there is a workaround:
1. Steps 1-3 in Reproduction.
2. Run `devenv.com /upgrade games.sln`.
3. `msbuild` will now build successfully.

### Screenshots
Before upgrade:
[games.sln.zip](https://github.com/mastercomfig/team-comtress-2/files/5272916/games.sln.zip)
![](https://user-images.githubusercontent.com/3462541/94090860-92b8e280-fdcb-11ea-9255-3d395e6c929a.png)

```
Microsoft (R) Build Engine version 16.8.0-preview-20452-03+5dee11854 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 9/23/2020 6:35:05 PM.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.10
```

After upgrade:
The sln works properly.
[games.sln.zip](https://github.com/mastercomfig/team-comtress-2/files/5272903/games.sln.zip)

### Setup Details
- *Server or client:* 
- *Operating system:* 
- *Team Comtress version:* 
- *Custom content:* 
- *Launch options:* 

- *Graphics driver:* 
- *DirectX level:* 

### Performance Details

- *GPU model:* 
- *CPU model:* 
- *RAM amount:* 
- *TF2 installed on:* 
- *TC2 installed on:* 
- *TC2 installation method:*

**Comment by maximsmol** [comment]
I do not think we really care about bugs in VPC, but I will let someone else chime in too

**Comment by Juesto** [comment]
I'd like to point out that this is the type of bug caused by users misusing vpc operations. no offense intended.

**Comment by Margen67** [comment]
> 
> 
> I'd like to point out that this is the type of bug caused by users misusing vpc operations. no offense intended.

What's the solution, then?

**Comment by Juesto** [comment]
> > I'd like to point out that this is the type of bug caused by users misusing vpc operations. no offense intended.
> 
> What's the solution, then?

Modifying vpc to support scenarios like those and using that version.
Or having VS2015 also installed on the CI.
