### ISSUE TITLE
C(++) Language Standard should automatically be set to C++17

### ISSUE THREAD

**Issue by Margen67** [mastercomfig/tf2-patches#319]
### Description
Projects (vcxproj) don't have the C(++) Language Standard set to C++17.
This makes setting it manually a requirement. (gross)

### Checklist
- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [x] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
1. https://github.com/mastercomfig/team-comtress-2/wiki/Windows-Build-Instructions#building up to Step 9.
2. Try to build.

#### Workaround(s):
1. Manually fix the C(++) standard in properties as described in Build Instructions (gross)
2. Add the following properties to each vcxproj manually (slow, also gross):
```
foreach-object { $a = $_.fullname; ( gc $a ) |
foreach-object { $_ -replace "</ClCompile>","`n      <LanguageStandard>stdcpp17</LanguageStandard>`n      <LanguageStandard_C>stdc17</LanguageStandard_C>`n    </ClCompile>" }  | 
set-content $a }
```

### Setup Details
- *Server or client:* 
- *Operating system:* 
- *Team Comtress version:* 
- *Custom content:* 
- *Launch options:* 

- *Graphics driver:* 
- *DirectX level:* 

### Performance Details

- *GPU model:* 
- *CPU model:* 
- *RAM amount:* 
- *TF2 installed on:* 
- *TC2 installed on:* 
- *TC2 installation method:*

**Comment by melvyn2** [comment]
I think this would fit the feature request template better, but too late. As for the actual issue, vpc doesn't explicitly set a language setting from what I can tell, and modifying it is out of scope last I checked. Unfortunately, changing it for each project with your script seems best.

**Comment by maximsmol** [comment]
Yeah VPC literally does not have an option to set this. Maybe we could roll out a tiny patch for it though or write a batch script to change the solution files
