### ISSUE TITLE
Create a standard community benchmark to make submiting results easy and fast

### ISSUE THREAD

**Issue by Kenajcrap** [mastercomfig/tf2-patches#330]
## Description

The easier it is to contribute to any project, the more people will contribute. In the case of TC2, while directly contributing to the code base depends on knowledge that most of the interested don't have, they can still contribute by sending feedback, the easiest to produce and most easily analyzable of which is benchmark results. However, to compare between TC2 and TF2 fairly one will have to use the same settings in both versions, reproduce the same load in both tests, make sure to disable any custom content, and this quickly becomes to much work for most people to bother doing. By automating and standardizing the benchmark there will be more contributions. 
Here is how I think this could be done:
### Important characteristics
- **Easy to use**: Ideally just double-click a file and let it run
- Fast. The quicker and less bothersome the benchmark is to run, the more people will do it
- Reproducible. The same test should be performed every time **both in TC2 and TF2**
- Granular. The more info can be garnered, the better.
- Unobtrusive. Should not modify the game files, at least not permanently
### Nice to haves
- Future proof, should keep working on TC2 and TF2 indefinitely
- Platform Agnostic. Should work the same on Linux and possibly Mac OS
- Simplicity. A simpler method will lead to more transparency

With that in mind, I outlined the methodology for 2 benchmarks; One completely automatic and hands-off, so anybody can run
and look at the results, and the other more granular but will involve input and sensibility from the player. I didn't bother to actually implement any of them yet because I wanna hear what everyone has to say before opening a pull request.
### Methodology: Simple Bench
- Include a standard demo file in future releases that contains a short (30 seconds max) burst of action in a newer map, with hats and unlock weapons. Here is an example demo:
- Include a the files `benchlow.cfg`, `benchmedium.cfg` and `benchhigh.cfg` in `tf\cfg` with low, medium and high config presets composed of only UI-available options.
- Include a `benchmark.bat` in the main TC2 dir that will:
  1- Ask the user to make sure cloud sync is turned off for TF2, close any running applications like browsers and discord and not touch the computer until the benchmark is done
  2- Rename TC2's current `tf\custom` to `tf\custom_backup` and `config.cfg` to `config_backup.cfg`
  3- Move `tf\custom_backup\tc2` back to `tf\custom\tc2`
  4- Start TC2 with the default parameters plus `+exec benchlow +fps_max 999 +timedemo standardbench`
  5- Wait for a new line containing `standardbench.dem` to appear in `tf\sourcebench.csv` using something like `findstr "standardbench.dem" tf\sourcebench.csv` then kill hl2.exe using `taskkill /F /IM hl2.exe`
  6- Repeat steps 4 and 5 for `benchmedium.cfg` and `benchhigh.cfg`
  7- Copy over `benchlow.cfg`, `benchmedium.cfg` and `benchhigh.cfg`  and repeat steps 2 through 6 for TF2
  8- Undo steps 2 and 3
  9- Create `communitybench.csv` on `benchmark.bat`'s dir by echoing the proper header and appending the last 3 entries of TC2's `sourcebench.csv` and TF2's `sourcebench.csv`
  10- Append other useful fields like OS version and CPU model using `systeminfo | findstr /R <regex pattern>`
  11- Pretty print some stats or comparisons for the user and ask them to upload the file to #comtress-analysis on mastercomfig's discord

This was the best way I could think of to capture performance numbers from TF2 without modifying the game or downloading extra tools. It might not be much but its so simple that even a child can contribute results. It might also serve as another way to confirm to a less informed user with straight numbers the performance increase of TC2 in their specific setup
### Methodology: Advanced Bench
- Include a standard demo file in future releases that contains a short (30 seconds max) burst of action in a newer map, with hats and unlock weapons. Here is an example demo:
- Include a the files `benchlow.cfg`, `benchmedium.cfg` and `benchhigh.cfg` in `tf\cfg` with low, medium and high config presets]
- Instruct the user to do the following:
  1- Download and install [FrameView](https://www.nvidia.com/pt-br/geforce/technologies/frameview/) (yes, even if you use an AMD card)
  2- Launch FrameView, set "Capture delay" to 0, "Capture duration" to `<standardbench.dem duration>` and take note of the "Benchmark Hotkey"
  3- Rename your config.cfg and launch TC2 adding the launch options `+exec benchhigh +fps_max 999 +playdemo standardbench` to `start_tf2.bat`
  4- As soon as the demo starts playing, press the benchmark hotkey and wait until the demo is over then quit (the benchmark stops automatically, no need to press the hotkey again at the end)
  5- Copy over `benchhigh.cfg` then do steps 3 and 4 on TF2.
  6- On FrameView, click on open folder, rename the resulting .csvs to `TC2_[version number].csv` and `TF2.csv` and upload them to #comtress-analysis (you can check which is which by looking at which file is older).

These instructions could be pinned on the discord and be available on the wiki with a link on the readme
### Things to be discussed
- ~~Have I wasted my time?~~ Is having a standard benchmark available on releases something useful for the contributors and the project?
- The exact demo to be used as standardbench.dem
  - Should it be a spec perspective or a player perspective? (specs render more of the game than players from what I can tell)
  - Map, player/bot count, etc
  - Should this use a demo at all? What are the differences between a demo and a live match? Networking?
- The presets to be used
- A way to find TF2's install directory, to copy over the presets in a batch script. While making sure the steps I suggested worked I could not find a way get a specific Steam game's install path, only custom library paths that could contain said game.
- Is FrameView the best option to capture frame data?
- Should there also be a bench run with the user's normal config and custom content as another point of comparison.

## Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [ ] This idea is for the code of the game, not for textures, sounds, or other resources.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).
- [x] This is obviously an improvement, not something that people commonly disagree on.

- [ ] This idea has been implemented in vanilla TF2.
- [x] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [ ] This idea has been implemented in a mod. 
- [ ] This feature has existed in the vanilla game but was removed.
- [x] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

## Alternatives

1. Dropping the advanced bench entirely, since the usefulness of having aggregate frame data as opposed to 1 or 2 runs here and there is questionable at best
2. Dropping `benchmedium.cfg` entirely to make the simple bench quicker.
3. Instead of using the generated sourcebench.csv, there could be a way to use RCON to spam the `stats` command on console during the demo and parse console.log for the results, that way you can get FPS over time instead of just an average and variance. But I don't know if that's worth the trouble.

**Comment by Kenajcrap** [comment]
After talking about this with @Yttrium-tYcLief  and doing some more testing myself, I've come to the conclusion that timedemo is even less useful than it seems.
I wrote the issue assuming it was a simple way to get an average number and even variance to compare across versions and specs and while 1 result is useless for analysis (as oppose to real frame time captures), the aggregate data would help illustrate the performance improvements across a variety of scenarios. However, upon closer inspection, timedemo is not at all representative of performance changes even when only compared to itself. It distorts the percentage of the difference in averages compared to a normal game and straight up stops representing the performance increase at lower graphic settings while the difference is clearly visible in normal gameplay.
So there doesn't seems to be a good option to benchmark the game natively without downloading other programs.
Besides that, other things that were brought up:
- Fixing #191 is not trivial and keeping it fixed through future may not be possible due to the nature of the changes being made to the game.
- The sourcemod plugin I was thinking of using to create bots with hats and different weapons and record a standard demo does not work in TC2's so the only option to measure the impact of hats (which is important imo) would be to setup a full playtest session and record there.

So with that in mind, what I propose can still be done when the time comes is making a standard for advanced benchmark only;
- IF there comes a version of TC2 which fixes #191 , setup a playtest and create a standard demo there. In the meantime, just a normal bot vs bot recorded in the last compatible version of TC2 will suffice
- Create a wiki page explaining how to take valid captures with FrameView or other decided tool
- Settle on at least a `benchlow.cfg` and `benchhigh.cfg` to use for captures

**Comment by uis246** [comment]
Also split measurements on cold-start(game start, no files in cache), warm-start(game (re)start, files cached) and in-game(game running, reopen demo)
