### ISSUE TITLE
CEngineTraceClient::GetWorldCollideable Assertion Failed

### ISSUE THREAD

**Issue by SizzlingCalamari** [mastercomfig/tf2-patches#333]
Repro: Start up the game and enter `map cp_badlands` in console. Spawn in as any class, type `exit` in console.
Build: 3f4b1760abef08a986ae4447330d3371ca737ad9 Debug x86
Error:
```
enginetrace.cpp (1327) : Assertion Failed: pUnk
```
Callstack:
```
>	engine.dll!CEngineTraceClient::GetWorldCollideable() Line 1327	C++
 	engine.dll!CEngineTrace::TraceRay(const Ray_t & ray, unsigned int fMask, ITraceFilter * pTraceFilter, CGameTrace * pTrace) Line 1688	C++
 	engine.dll!DAS_UpdateRoomSize(das_room_t * proom) Line 3702	C++
 	engine.dll!DAS_CheckNewRoomDSP() Line 4149	C++
 	engine.dll!S_Update_New() Line 6266	C++
 	engine.dll!S_Update_Thread() Line 6793	C++
 	engine.dll!CFunctor0<void (__cdecl*)(void),CRefCounted1<CFunctor,CRefCountServiceBase<1,CRefMT>>>::operator()() Line 435	C++
 	engine.dll!FunctorExecuteThread(void * pParam) Line 1155	C++
 	tier0.dll!ThreadProcConvert(void * pParam) Line 114	C++
 	tier0.dll!thread_start<unsigned int (__stdcall*)(void *),1>(void * const parameter) Line 97	C++
 	[External Code]	
 	kernel32.dll![Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	Unknown

```

**Comment by SizzlingCalamari** [comment]
Sound thread is still processing while the local player is destroyed. Gets a null player back and asserts.

**Comment by Yttrium-tYcLief** [comment]
Might be fixed with the threading fixes coming to 0.0.18.

**Comment by mastercoms** [comment]
This one will be harder to fix. We can do a brutal hack and disable threaded sound updates on level shutdown, and turn it back on during level startup, which will also fix soundscapes playing during a map load, or we can add a global mutex for traces and entities.

**Comment by int-72h** [comment]
@mastercoms what is the disadvantage of using a mutex rather than the hack?

**Comment by mastercoms** [comment]
It's messy to do and will add extra overhead as 99% of cases will never need a mutex.

**Comment by int-72h** [comment]
The hack seems better then I guess- though I assume that wont be easier either.
Hacks are what we're avoiding iirc but a mutex seems wasted
