### ISSUE TITLE
DXMath usage clean up

### ISSUE THREAD

**Issue by melvyn2** [mastercomfig/tf2-patches#341]
### Description
Currently, linux builds on master fail due to missing DXMath vector functions, due to this include not being included. TC2's dxmath usage does not seem fully 'ready' (according to #339), so this issue was created to document issues related to DXMath on POSIX platforms.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] ~This issue occurs on the latest vanilla TF2 update.~
- [ ] ~This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).~
- [ ] ~This issue occurs with DirectX level 100.~ (ToGL limits to 90)
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [ ] ~This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.~
- [ ] ~This issue occurs when using a listen server (using the `map` command ingame).~
- [ ] ~This issue occurs when using a dedicated server.~
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
Try to build on the build-linux branch after rebasing onto master; it will fail due to the `DirectXMath.h` header not being included in `ssequaternion.h`.

### Setup Details
- *Operating system:* `5.8.10-lqx1-1-lqx #1 ZEN SMP PREEMPT Thu, 17 Sep 2020 14:35:33 +0000`
- *Team Comtress version:* 4ef0b43

**Comment by mastercoms** [comment]
Should be enough for POSIX in this update: https://github.com/mastercomfig/team-comtress-2/commit/1a6ce9f14d05399f8813241dab96fb51155c0469

**Comment by int-72h** [comment]
@melvyn2 does 1a6ce9f solve the issues?

**Comment by melvyn2** [comment]
Yes, that commit does fix the include problem.
