### ISSUE TITLE
Bugs On Main Menu with the playermodels 

### ISSUE THREAD

**Issue by Melonenyoshi** [mastercomfig/tf2-patches#390]
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue occurs on the latest vanilla TF2 update.
- [x] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1.

### Screenshots

![20201002070904_1](https://user-images.githubusercontent.com/68987602/94890004-56961980-047e-11eb-802f-d5a41d1db178.jpg)
![20201002070906_1](https://user-images.githubusercontent.com/68987602/94890006-57c74680-047e-11eb-9373-aa29418fe384.jpg)
![20201002070907_1](https://user-images.githubusercontent.com/68987602/94890007-585fdd00-047e-11eb-9853-9250f7826d18.jpg)
![20201002070739_1](https://user-images.githubusercontent.com/68987602/94890008-585fdd00-047e-11eb-8dd7-469a5655f30d.jpg)
![20201002070740_1](https://user-images.githubusercontent.com/68987602/94890009-58f87380-047e-11eb-8610-e6351290f1cd.jpg)
![20201002070748_1](https://user-images.githubusercontent.com/68987602/94890011-58f87380-047e-11eb-947a-00da0c3850fb.jpg)
![20201002070811_1](https://user-images.githubusercontent.com/68987602/94890012-59910a00-047e-11eb-8307-323a677fe5ba.jpg)
![20201002070812_1](https://user-images.githubusercontent.com/68987602/94890013-59910a00-047e-11eb-9542-0a8f2f1e008d.jpg)
![20201002070815_1](https://user-images.githubusercontent.com/68987602/94890015-5a29a080-047e-11eb-96dd-403e7fe32e42.jpg)

**Comment by Melonenyoshi** [comment]
just if you dont already know about this

**Comment by melvyn2** [comment]
What is the bug?

**Comment by Yttrium-tYcLief** [comment]
There are plenty of bugs. Items and miscs not using the right team color, the model being stuck in reference pose or looping bad animations, weapons not even being properly attached to bones sometimes, plus the fact that the whole viewport seems to be horizontally stretched (like using 4:3 on a 16:9 monitor).

**Comment by Melonenyoshi** [comment]
> What is the bug?

Look at screenshots pls

**Comment by Melonenyoshi** [comment]
> There are plenty of bugs. Items and miscs not using the right team color, the model being stuck in reference pose or looping bad animations, weapons not even being properly attached to bones sometimes, plus the fact that the whole viewport seems to be horizontally stretched (like using 4:3 on a 16:9 monitor).
> 
> It would be way too much to create a new issue/report for each bug, but it would be good to make a checklist at the top of this report so that each one can be checked off over time.

Ye but I don't know every bug so cant we use the comment section to make this

**Comment by micwoj92** [comment]
> > There are plenty of bugs. Items and miscs not using the right team color, the model being stuck in reference pose or looping bad animations, weapons not even being properly attached to bones sometimes, plus the fact that the whole viewport seems to be horizontally stretched (like using 4:3 on a 16:9 monitor).
> > It would be way too much to create a new issue/report for each bug, but it would be good to make a checklist at the top of this report so that each one can be checked off over time.
> 
> Ye but I don't know every bug so cant we use the comment section to make this

Ye, but you can just edit post when a new bug gets discovered.

**Comment by Yttrium-tYcLief** [comment]
I'll make a list tomorrow.

**Comment by Melonenyoshi** [comment]
Thank you

**Comment by micwoj92** [comment]
> I'll make a list tomorrow.

Did you do it?

**Comment by Sirbucket** [comment]
Oh I just had this happen to me, gonna close the one I just opened then.
