### ISSUE TITLE
Switching to full screen does not apply unless you revert back to windowed mode.

### ISSUE THREAD

**Issue by Wosheereal** [mastercomfig/tf2-patches#420]
### Description
same as title.

### Checklist

- [X] None of the open *or* closed issues document this problem.
- [X] This is a bug, not a new idea.
- [X] This is objectively a bug, and not something that people commonly disagree on.
- [X] This issue occurs on the latest Team Comtress release, or the `master` branch.

- [ ] This issue occurs on the latest vanilla TF2 update.
- [X] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [X] This issue occurs when using no custom content.
- [X] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Open TC2
2. Switch to full screen mode and realize it did not apply.
3. Revert back to windowed and try to go to full screen again and it works.

#### Client Settings

- *Server or client:* <Client>
- *Operating system:* <Win10>
- *Team Comtress version:* <0.1.6>
- *Custom content:* <E.V.E hud>
- *Launch options:* <None>
#### Driver Version

- *Graphics driver:* <456.38>
- *DirectX level:* 
#### Hardware Specs

- *CPU model:* 
- *GPU model:* <NVIDIA GTX 970 MSI 4GB>
- *RAM amount:* <32GB>
- *TF2 install location:* <USB Flash Drive>
- *TC2 install location:* 
- *TC2 installation method:* <Basic>

**Comment by Kenajcrap** [comment]
I've also experienced this problem. Even using mat_setvideomode, this still happens

**Comment by treacherousfiend** [comment]
Unless it got changed, I think the game is currently foced to borderless windowed due to fullscreen being bugged.
So this is sort of intentional?

**Comment by Yttrium-tYcLief** [comment]
Is this still present as of the latest build (0.1.12), since fullscreen behavior was changed in 0.1.11?

> Fullscreen support is now restored, as crashes associated with it have been resolved.
