### ISSUE TITLE
Incorrect loading of workshop soundscripts and soundscapes

### ISSUE THREAD

**Issue by KaydemonLP** [mastercomfig/tf2-patches#468]
In Live TF2, workshop maps have the issue of not being able to load soundscapes and soundscripts, or rather, the filepaths they are trying to load are incorrect.
To make it short, the function they use is engine->GetLevelName(), which returns workshop/mapname.ugcWorkshopID rather than maps/mapname.bsp.
This causes soundscripts to load maps/workshop/mapname.txt ( the ugc part is stripped via Q_StripExtension ) and scripts/soundscapes_workshop/mapname.ugcWorkshopID
This makes it really inconvenient for mappers ( see all the maps on the workshop that say Soundscapes don't work ) and is probably unintentional, because there actually is code to strip these parts away from the mapname to get the actual result, which is used in other places ( the scoreboard for example ).
So the best way to fix these would be using that function in these places:
File: shared/SoundEmitterSystem.cpp, line 267
replace
`Q_strncpy( mapname, engine->GetLevelName(), sizeof( mapname ) );`
with
`Q_strncpy( mapname, GetMapDisplayName( engine->GetLevelName() ), sizeof( mapname ) );`
File: client/c_soundscape.cpp, line 306
`const char *mapname = MapName();`
with
`const char *mapname = GetMapDisplayName( MapName() );`

I personally would also replace MapName() with engine->GetLevelName() to make it more consistant with other functions, but thats up to you.

**Comment by mastercoms** [comment]
Is the workshop ID static?

**Comment by agrastiOs** [comment]
Yes.

**Comment by mastercoms** [comment]
Isn't there a probability of collision between map names then? I would assume the strip extension removing the ID is a bug, rather than what's happening in soundscapes.

**Comment by KaydemonLP** [comment]
The ID stripping is a unintentional side-effect of the Function intending to remove the .bsp extention, which is not present when you get a workshop map's LevelName.
It would also not cause collision between map names, because these soundscripts are packed into the map, and only get loaded when that specific map is loaded aswell.
The only time a collision could happen if a map is named like a map that exists in live TF2, for example if a workshop map had the name ctf_2fort.bsp.
Though in that case regular override rules apply, and the soundscape packed into the map would temporarily override the base one, which is something that already happens if you do the same thing regularly ( outside the workshop ).

**Comment by KaydemonLP** [comment]
https://github.com/mastercomfig/team-comtress-2/blob/639a3c5ca3c73a8845d5fcaf13625f5fe862442b/game/shared/SoundEmitterSystem.cpp#L307

This is the line that removes the extention btw
