### ISSUE TITLE
Engineer holds Destruction PDA incorrectly using 3D playermodels for HUD

### ISSUE THREAD

**Issue by Platina6978** [mastercomfig/tf2-patches#475]
### Description
When using 3D player models in the HUD, the engineer will hold the Destruction PDA as if it was a wrangler (the Construction PDA is fine however).

### Checklist

- [X] None of the open *or* closed issues document this problem.
- [X] This is a bug, not a new idea.
- [X] This is objectively a bug, and not something that people commonly disagree on.
- [ ] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [X] This issue occurs on the latest vanilla TF2 update.

- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [X] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues). [#2564](https://github.com/ValveSoftware/Source-1-Games/issues/2564)
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [X] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Enable 3D player models for the HUD
2. Select engineer and take out the Destruction PDA
3.

### Screenshots

![destruction PDA](https://user-images.githubusercontent.com/71837773/97110496-ee7fcf80-16d9-11eb-960a-7fb0759087cf.jpg)

#### Client Settings

- *Server or client:* 
- *Operating system:*  Windows 7
- *Team Comtress version:* 
- *Custom content:*  customized flawhud and autoexec
- *Launch options:*  -console -novid -nojoy -nosteamcontroller -nohltv -particles 1 -no_texture_stream
#### Driver Version

- *Graphics driver:* 
- *DirectX level:* 
#### Hardware Specs

- *CPU model:* 
- *GPU model:* 
- *RAM amount:* 
- *TF2 install location:* 
- *TC2 install location:* 
- *TC2 installation method:*

**Comment by Ashetf2** [comment]
Fixed in retail tf2

"Fixed the Engineer's Destruction PDA using the wrong animation in the 3D HUD player model (community fix from gidi30)"
