### ISSUE TITLE
High Mouse Polling Rates Lag the game

### ISSUE THREAD

**Issue by rcmaehl** [mastercomfig/tf2-patches#485]
### Description
Having a mouse with a high polling rate seems to cause the game to lag. This lag has been reduced slightly but still exists in comtress.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs on the latest vanilla TF2 update.

- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100. - ???
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Have 1000hz polling rate mouse
2. Aggressively move mouse
3. Watch FPS dip significantly

### Screenshots
Soon™

#### Client Settings

- *Server or client:* Client
- *Operating system:* Windows 10 19041.572
- *Team Comtress version:* 0.3.1
- *Custom content:* mastercomfig ultra
- *Launch options:* start_tf2.bat
#### Driver Version

- *Graphics driver:* 20.4.2
- *DirectX level:* default
#### Hardware Specs

- *CPU model:* R7 1800X
- *GPU model:* RX480 8GB
- *RAM amount:* 32GB
- *TF2 install location:* SSD
- *TC2 install location:* SSD
- *TC2 installation method:* Basic

**Comment by treacherousfiend** [comment]
On a whim, I decided to test this out a bit, and this doesn't seem to be a TC2 or TF2 issue. It appears to be a windows issue, as when moving my mouse frantically I sometimes see my CPU usage for the program my mouse is over spike 10%.
This even happens on default windows apps like windows explorer.

I attempted to report this bug to microsoft, but wasn't able to contact them

**Comment by mastercoms** [comment]
Fixed
