### ISSUE TITLE
have team comtress 2 use the ammo pickup system from team fortress 2 classic

### ISSUE THREAD

**Issue by ghost** [mastercomfig/tf2-patches#525]
### Description

what the title says, i will upload two videos so that you can make a comparrison between the two systems
### Checklist

- [x] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [x] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [x] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [x] This idea is for the code of the game, not for textures, sounds, or other resources.
- [ ] This idea has been implemented in vanilla TF2.
- [ ] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [x] This idea has been implemented in a mod. https://tf2classic.com/
- [ ] This feature has existed in the vanilla game but was removed.
- [ ] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Screenshots

https://www100.zippyshare.com/v/0F4J0ze9/file.html - team fortress 2 classic system
https://www80.zippyshare.com/v/zpP7PzTg/file.html - team fortress 2 system

**Comment by higgy999** [comment]
Could you put the videos on YouTube instead? The website keeps giving popups and button redirects.

**Comment by vlad55523** [comment]
@higgy999  https://youtu.be/kkyuStHxqyc - tf2c reload system
https://youtu.be/knAGnjIjh9A - tf2 reload system
i think it's a game change and mastercoms said she will not accept this type of changes anymore in her discord, it just gets rid of having to reload before picking up ammo and that would be CLEARLY an improovement

**Comment by higgy999** [comment]
Normally I would say that this is a bug when the game adds up the ammo for a weapon but in tf_port (2007/2008 tf2) this feature isn't there which makes me think that its a tf2c exclusive. I don't even think this would be unbalanced. Weapons dependent on their clip to stay balance are still balanced because you would still have to reload making it a non significant change. It might make fast reloading weapons overpowered though.

**Comment by vlad55523** [comment]
by "fast reloading weapons" you mean the weapons which reload their entire clip at once such as the bows, smg's, pistols and syringe guns?

**Comment by higgy999** [comment]
> by "fast reloading weapons" you mean the weapons which reload their entire clip at once such as the bows, smg's, pistols and syringe guns?

I mean the Force of Nature and that other gun with a clip of 4 and has the shove. Forgot the name. Those weapons do lots of damage, have small clips, and reload faster than stock.

**Comment by vlad55523** [comment]
i don't think i see how this would be unbalanced for the force a nature the soda popper and the shortstop (weapons meeting your criteria), would you mind explaining how would the new system make them overpowered?
