### ISSUE TITLE
fixing/adding animations for class selection screen

### ISSUE THREAD

**Issue by condor00fr** [mastercomfig/tf2-patches#544]
the class selection screen animations are just broken, they always freeze and they they don't even play the old  soundeffects  from 2007-2015, it would be nice to see bugs fixes for this, also, some weapons don't even have animations for them, Tf2c had the idea to add some new ones like for the huntsman, and it looks really nice

-it's a bunch of bugs
-was seen in mods
-dosn't affect gameplay in any way-

**Comment by mastercoms** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2153744818
