### ISSUE TITLE
Game crashes after bot match ends (Unsure as to why)

### ISSUE THREAD

**Issue by Sirbucket** [mastercomfig/tf2-patches#573]
### Description

Game crashed at the end of a pl_upward expert difficulty bot match with 24 players.
### Checklist

- [x] None of the open *or* closed issues document this problem[x].
- [x] This is a bug, not a new idea[x].
- [x] This is objectively a bug, and not something that people commonly disagree on[x].
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch[x].

- [ ] This issue occurs on the latest vanilla TF2 update.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources. (Unsure, but probably.)
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [x] This issue occurs with DirectX level 100 [x].
- [ ] This issue occurs when using no custom content[x].
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options[x].
- [x] This issue occurs when using a listen server (using the `map` command ingame). (Unknown, if the offline bot matches use map then yes)
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Play upward in bot mode with expert difficulty and 24 bots.
2. Finish the game
3. Maybe it'll crash

### Screenshots

Crashed and had no error.

### Setup Details
Ryzen 5 2400G
GTX 1060
16GB of RAM
SSD and HDD, game is on HDD

#### Client Settings

- *Server or client:*  Client
- *Operating system:*  W10
- *Team Comtress version:* a4ae532
- *Custom content:* None
- *Launch options:* None
#### Driver Version

- *Graphics driver:*  
- *DirectX level:*  
#### Hardware Specs

- *CPU model:* 
- *GPU model:* 
- *RAM amount:* 
- *TF2 install location:* 
- *TC2 install location:* 
- *TC2 installation method:* 
-

**Comment by Sirbucket** [comment]
It just crashed as the match ended and I don't know why.

**Comment by GnKenobi** [comment]
I tried this and it didn't crash. Seems to be an issue on your end.
