### ISSUE TITLE
If a medic heals a spy in disguise, The medic gets an instant disguise

### ISSUE THREAD

**Issue by thatsnotsoup** [mastercomfig/tf2-patches#578]
### Description
New players playing medic  and messing up a Spy's disguise is an annoying problem in Public servers, So this improvement will actively fix that problem by offering a medic healing a Spy a disguise that goes away as soon as the Spy stops disguising.

### Checklist
- [] None of the open *or* closed issues document this idea.
- [x] This is a new idea, not a bug.
- [] This idea does not seriously affect game balance.
- [x] This is obviously an improvement, not something that people commonly disagree on.
- [] This is not an idea for new game content (e.g. new weapons, maps, sounds).

- [] This idea is for the code of the game, not for textures, sounds, or other resources.
- [] This idea has been implemented in vanilla TF2.
- [] There is proof that this idea is well liked (e.g. a history of use of a similar mod in a competitive league).
- [] This idea has been implemented in a mod.
- [] This feature has existed in the vanilla game but was removed.
- [] This idea is for internal procedures or tooling (e.g. improving the build process, supporting new systems).

### Alternatives
1.  Simply refuse a Medic the ability to heal disguised Spies
2. Disable Ubercharge and Ubercharge build up for a Medic when healing a disguised Spy as a punishment
3. Disable all Medigun abilities if a Medic is healing a disguised Spy, making it a useless idea to heal one

**Comment by treacherousfiend** [comment]
This is a balance change, TC2 is only for bug fixes and optimizations.
