### ISSUE TITLE
Equilizer

### ISSUE THREAD

**Issue by Kidcoder64** [mastercomfig/tf2-patches#587]
### 
Could you make some kind of visual indication of how much damage the Equalizer does, such as literally displaying it's current damage output, or a meter that gives you an Idea of how much more damage your doing, maybe making it colored like the Demoman's shield charge, red for less damage than stock, yellow for around the same damage, and green for more damage. All that said, you're doing a good job guys! Keep doing what your doing.

**Comment by melvyn2** [comment]
damage indicators exist in stock tf2 already and in tc2, in advanced options. out of scope anyways.

**Comment by Kidcoder64** [comment]
> damage indicators exist in stock tf2 already and in tc2, in advanced options. out of scope anyway
I'm talking about before you deal damage so that you know how much damage your going to do, not for ranged weapons, just for melee.

**Comment by Sirbucket** [comment]
As nice as it would be to have, the conversions that the equalizer has is not pretty and the bar would look strange, I'm gonna give that a pass.
