### ISSUE TITLE
Huntsman hitbox glitch

### ISSUE THREAD

**Issue by condor00fr** [mastercomfig/tf2-patches#600]
so The youtuber Delfy made a recent video that shows why the Lucksman is a buggy mess : valve has give the same headshoy hitbox for all classes.

https://www.youtube.com/watch?v=ia17FJ0TUy8

**Comment by micwoj92** [comment]
Who is Delfy?

**Comment by wgetJane** [comment]
this isn't a bug or glitch, it's just how the arrows work and it's working as intended

from the description of this video: https://youtube.com/watch?v=E4JHCk7RAm0
> Like other projectiles, arrows use a player's bounding box instead of their hitboxes for collision detection.
>
> Upon intersecting with a player's bounding box, the game tries to attach the arrow to the player model. It tries to figure out which body part it should be attached to.
>
> A raytrace is performed using the arrow's position and velocity at the point of impact, and when it intersects with a hitbox then the arrow is attached to that.
>
> Otherwise, the game loops through all of the player's hitboxes. For each of them, a raytrace is performed from the arrow to their centre, getting the distance until intersection. The arrow is attached to the one with the shortest resulting distance.
>
> If the arrow is attached to the head hitbox, then it's considered a headshot.

**Comment by theasin** [comment]
This is actually not a bug, but a special thing. It acts both as a projectile and a hitscan bullet at the same time. When the arrow hits player's bounding box (the thing that makes projectile-based weapons work), arrow will connect to the nearest hitbox. Any problems?

**Comment by rcmaehl** [comment]
Due to the travel time of the arrow it makes no sense to remove the projectile attribute of it, but due to the nature of projectiles, there's no reason why hitscan math shouldn't be used.
