### ISSUE TITLE
Conditional branch in `CTFBotMedicHeal::SelectPatient` is unreachable.

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [mastercomfig/tf2-patches#609]
### Description

`CTFBotMedicHeal::IsGoodUberTarget(CTFPlayer who*)` always returns false. As a result the code in `game/server/tf/bot/behavior/medic/tf_bot_medic_heal.cpp` at lines 266 to 270 will never run, because the return value of `IsGoodUberTarget()` is used in an AND operation.

### Checklist

- [X] None of the open *or* closed issues document this problem.
- [X] This is a bug, not a new idea.
- [X] This is objectively a bug, and not something that people commonly disagree on.
- [X] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [X] This issue occurs on the latest vanilla TF2 update.

- [X] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [X] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Compile source code.
2. Load a map.
3. Create a medic bot, a bot as a class that is considered a 'good uber target' by `IsGoodUberTarget()`, and a bot as a class that is not considered a good uber target, which includes medic, sniper, engineer, scout, and spy.
4. Wait for medic to build full uber.

Expected behavior: The medic bot does not switch off the patient bot that is considered a good uber target by `IsGoodUberTarget()`.
Actual behavior: The medic bot switches off the patient bot bot that is considered a good uber target by `IsGoodUberTarget()`, even when the medic bot has full ubercharge.

#### Client Settings

- *Server or client:* 
- *Operating system:* 
- *Team Comtress version:* 
- *Custom content:* 
- *Launch options:* 
#### Driver Version

- *Graphics driver:* 
- *DirectX level:* 
#### Hardware Specs

- *CPU model:* 
- *GPU model:* 
- *RAM amount:* 
- *TF2 install location:* 
- *TC2 install location:* 
- *TC2 installation method:*

**Comment by mastercoms** [comment]
It's unknown if intended for MvM or not, so closing
