### ISSUE TITLE
Beard/facial felxes cosmetics animation

### ISSUE THREAD

**Issue by SharSash** [mastercomfig/tf2-patches#611]
Description:
In the game most cosmetic items that use facial flexis don't work properly. They don't exactly follow actual chracter animation as if they are not correctly locked causing various visual and item clipping issues. Also it seems game uses character selection screen as animation refrence for those items rather than dynamicalyy rendering in the game.

### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs on the latest vanilla TF2 update.

- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [ ] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

Screenshots:
Screenshot taken in the team comtress' latest release by 29/11/2021
item-example used: scotch saver
![image](https://user-images.githubusercontent.com/95248273/143931110-6583d25c-241d-4ea1-a4b4-3ab46f470cab.png)

**Comment by sticks-stuff** [comment]
Should be noted that this only happens client side
