### ISSUE TITLE
aclocal-1.14 is missing on your system

### ISSUE THREAD

**Issue by xero-lib** [mastercomfig/tf2-patches#614]
### Checklist

- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch. (it occurred on the "main" branch)

- [ ] This issue occurs on the latest vanilla TF2 update.
- [ ] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [ ] This issue occurs when using no custom content.
- [ ] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [ ] This issue occurs when using a listen server (using the `map` command ingame).
- [ ] This issue occurs when using a dedicated server.
- [x] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction

1. Download source
2. Attempt to run build.sh on Arch Linux

### Screenshots

![image](https://user-images.githubusercontent.com/54485853/152631388-825640d7-4d7b-4175-8eb0-42c2f9a8ab78.png)

**Comment by clubby789** [comment]
Running `autoreconf` in `src/thirdparty/protobuf-2.6.1` fixed this for me
