### ISSUE TITLE
Some files are not encoded in UTF-8

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/tf2-patches#70]
**Describe the bug**
Some files, for example game/client/playerspawncache.h are not encoded in UTF-8, that can cause compatibility issues.

**How you encountered the issue**
I opened one file and GitHub said:
![image](https://user-images.githubusercontent.com/45581170/92771757-73699080-f39b-11ea-92cb-8e76c9350d36.png)

**Screenshots**
See above.

**Desktop (please complete the following information):**
* Team Comtress version (don't say latest, say the actual version): N/A
* Custom content (if any): N/A
* DX level: N/A
* Launch options: N/A
* Operating system (OS): N/A
* Graphics card (GPU): N/A
* Graphics driver version: N/A
* Processor (CPU): N/A
* TC2 on HDD or SSD: N/A
* Memory (RAM) size in MB or GB: N/A

**Comment by micwoj92** [comment]
@Yttrium-tYcLief this is not really tf2 issue. It has no effect on gameplay. Just development.

**Comment by Yttrium-tYcLief** [comment]
I'm just tagging it as something that needs to get fixed, and figured it also applies to live TF2. "TF2 issue" doesn't necessarily mean gameplay issue.
