### ISSUE TITLE
[Bug fix request] Coaching accessibility

### ISSUE THREAD

**Issue by OverwatchVoice** [mastercomfig/tf2-patches#77]
**Is your feature request related to a problem? Please describe.**
Coach mode is currently impossible to access in official lobbies, as they require the player to be in matchmaking to join.
There's a plethera of other bugs, such as the coach and studnet flags being reset at mapchange, the student outline persisting, etc.

**Describe the solution you'd like**
Self explanatory. Find a workaround to allow a coach to join valve's matchmaking servers, and, where possible, fix the bugs when actually coaching

**Comment by micwoj92** [comment]
is there at least 1 person that uses that feature?

**Comment by RealPortalPlayer** [comment]
> is there at least 1 person that uses that feature?

theres no conclusive answer if people use this feature or not if said feature doesnt even work most of the time

**Comment by micwoj92** [comment]
> > is there at least 1 person that uses that feature?
> 
> theres no conclusive answer if people use this feature or not if said feature doesnt even work most of the time

Coaching button isn't really noticeable on the main menu and only thing this gives is free wallhack.

**Comment by Yttrium-tYcLief** [comment]
Since this relies on the matchmaker, this will likely be impossible to test in TC2.
