### ISSUE TITLE
Game crashed to desktop on offline server

### ISSUE THREAD

**Issue by Thucket** [mastercomfig/tf2-patches#80]
**Describe the bug**
The game was running perfectly. The fps was rock solid and that was with 8x MSAA. It was very impressive. But, while rocket jumping on an offline server, after about 15 minutes of use the game crashed to desktop. Sound stopped before the program crashed.

**How you encountered the issue**
I'm not sure, all I was doing was playing on an offline plr_hightower server with no bots. I was using the rocket jumper, had an unusual kill-a-watt, a skinned shotgun (that wasn't displayed but I'm sure you're aware of that), and escape plan. 

**Desktop (please complete the following information):**
* Team Comtress version: 0.0.16
* Custom content (if any): I deleted my custom folder before launching
* DX level: DirectX 9, Hardware Level 10
* Launch options: None set, but my original install had "-dxlevel 95 -fullscreen -w 1920 -h 1080 -novid -high -nojoy -nosteamcontroller -nohltv -particles 1 -nostartupsound -freq 120"
* Operating system (OS): Windows 10 19041.450 updated on 8/22/2020
* Graphics card (GPU): GTX 1060 6gb
* Graphics driver version: 452.06
* Processor (CPU): i5 3470
* TC2 on HDD or SSD: SSD with no DRAM cache
* Memory (RAM) size in MB or GB: 12gb of DDR3

I know this isn't very helpful but I want to contribute anyway I can

**Comment by mastercoms** [comment]
You launched through start_tf2.bat, right? If so, those launch options wouldn't be used.
