### ISSUE TITLE
Rewrite the Tutorial to include more information

### ISSUE THREAD

**Issue by Thucket** [mastercomfig/tf2-patches#87]
**Is your feature request related to a problem? Please describe.**
New players need to take a 3 hour deep dive on Youtube before they can even start playing the same game as other players. TF2 has a critical lacking in information for new players, and the tutorial is still stuck in 2007.

**Describe the solution you'd like**
The text written into the original tutorial could be rewritten to include mechanics like rocket / sticky jumping, the mechanics of backstabbing, or sentry and dispenser placement. Possibly (maybe) tutorials could be made for Pyro (airblast), Sniper (damage numbers and chargetime), and Medic (importance of ubercharge), which all require their own explanations on their own.

**Describe alternatives you've considered**
Rewrite the text used in the Tutorials to be more up to date.

**Additional context**
Considering it has 2.6 million views you've probably already seen this video, but it has lots of good ideas that ought to reiterated https://www.youtube.com/watch?v=hj6duP3Ynt0&t=222s

**Comment by Yttrium-tYcLief** [comment]
This would be a substantial undertaking, and while pretty much everybody would be all for it, it sort of falls outside of the scope of this particular project. I'll wait for more feedback before dismissing it though.

**Comment by micwoj92** [comment]
@Yttrium-tYcLief I think the issue is that this ticket is basically 2 requests in one. One being the in game tutorial and second being the tips displayed when loading map. I think it should be splitted in 2.

**Comment by Yttrium-tYcLief** [comment]
Both portions of the request sort of fall outside of the scope of this project. If this takes off and gets Valve support, and we start working on a modern version of the game, it could certainly be looked at, but both a full tutorial *and* improved tips fall outside of the scope currently.
